site_name: pandaid-rest-api
site_description: REST API backend for Pand--Aid pandemic response app
repo_url: https://github.com/Pand-Aid /pandaid-api
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/Pand-Aid ">Pand-Aid </a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
